title: Vault-Tec Terminal
description: Professional penetration tester portfolio
baseurl: ""
url: "https://redteamer403.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  notes:                # Define the _notes collection
    output: true        # Render files in _notes as individual pages
    permalink: /notes/linux/enum/  # Set URL structure

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/