title: Vault-Tec Terminal 
description: RedTeamer403 Security Portfolio
baseurl: ""
url: "https://redteamer403.github.io"
author: RedTeamer403

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tag
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: bash

# Include notes directory
include:
  - _layouts
  - notes
  - posts
  - tools
  - assets/file
  - assets/images

sass:
  sass_dir: assets/css
  style: compressed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/